### PR TITLE
Export env variable 'XCODE_VERSION'  for selected xcode version

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by bobergj** [comment]
This would be interesting for us as well, but I think it the variable be called `XCODE_VERSION`.

**Comment by halx99** [comment]
> This would be interesting for us as well, but I think it the variable be called `XCODE_VERSION`.

Agree, will change it

**Comment by halx99** [comment]
> This would be interesting for us as well, but I think it the variable be called `XCODE_VERSION`.

Done.

**Comment by maxim-lobanov** [comment]
Hey, the action already set output variables: https://github.com/maxim-lobanov/setup-xcode/blob/master/src/setup-xcode.ts#L37
These variables can be consumed in next steps. Does this approach work for you?

**Comment by halx99** [comment]
> Hey, the action already set output variables: https://github.com/maxim-lobanov/setup-xcode/blob/master/src/setup-xcode.ts#L37 These variables can be consumed in next steps. Does this approach work for you?

works, thanks

**Pull request closed without merging**
