### PR TITLE
Implement "latest-stable" support

### PR DESCRIPTION
**Pull request by maxim-lobanov**
`setup-xcode v1.0` supports `latest` keyword that points to the latest Xcode installed on image (including beta releases like `Xcode_12_beta.app`.
It could be useful to have additional keyword that will point to latest stable Xcode. It will cover use-cases when new stable version is available on Hosted GitHub images but is not set as default yet.

Not sure about best naming so decided to use `latest-stable`

### CODE REVIEW

**Comment by mikehardy** [comment]
@maxim-lobanov just commenting to say 1) thanks for this action and 2) I'm using latest-stable feature successfully in react-native-firebase where it is resolving issues for us (thus the thanks)

One interesting tidbit is that it resolves to 12.0.0 right now while on my desktop it is `Version 12.0.1 (12A7300)` but I suppose that is completely out of the action's control and is due to the GitHub runners just not being updated.

Cheers

**Comment by maxim-lobanov** [comment]
@mikehardy ,  thank you for warm words :) 
Unfortunately, 12.0.1 is not available on GitHub runners yet. The new MacOS image with Xcode 12.0.1 will be deployed on Tue. Also it will contain 12.1 GM and 12.2 beta 3. You can track progress in https://github.com/actions/virtual-environments/issues/1797 .

Such delays are not ordinary for GitHub Actions. Usually, new Xcode versions are available in ~3 days after release but there were some issues with Python and some infrastructure issues recently that postponed deployments.

I considered adding installation Xcode in runtime in this action if it is not installed on image but it takes about ~10-15 minutes for every build and I am not sure that it is acceptable considering cost of MacOS minutes in GitHub

**Comment by dentuzhik** [comment]
@maxim-lobanov while installation of Xcode in runtime doesn't seem like a reasonable option for cloud runs, it might be a very useful addition for self-hosted runners, e.g. as an opt-in feature. If it would install Xcode and would be able to consume it later on, it would ease an effort of manually installing Xcodes.

_We currently use a no-modifications-fork of this action (the one before the PR which checked versions from Xcode package itself) and it had no issues of switching versions for a self-hosted MacMini._

If you are to implement this feature, I would gladly provide review feedback and test it on our machines :)

**Comment by maxim-lobanov** [comment]
Hm, interesting, I didn't consider using this task on self-hosted runners. Mostly because installation of Xcode on hosted runners are pretty tricky: https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/xcode-tools.sh and could be different from self-hosted runners.

@dentuzhik , Can't promise anything but could you please log an issue in this repository and I will think over this request. Also it would be very helpful if we may share the structure of your Xcode installation (naming and etc).

P.S. Just for curiosity, why do you use fork of this action? If you worry that you can be broken by any new changes, you can just pin specific version like `v1.2` (or even specific commit)

**Comment by mikehardy** [comment]
Macos minute's are free for open source 😁, there is another less popular xcode action that does install. Might be able to copy that and offer it with the appropriate 'probably only useful to manually test forward ports / this will be so slow...' type warning. But this isn't a real need for me. The action works great first time and meets our needs 💪

**Comment by dentuzhik** [comment]
> Mostly because installation of Xcode on hosted runners are pretty tricky: https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/xcode-tools.sh and could be different from self-hosted runners.

Well, I think there's no significant difference in Xcode installations in that sense, you need to download a `.xip` from developer portal and put into a correct place. open it, license, install CLI extensions, etc. Same thing with username/password, and it would not be a problem to store it as CI env variables.

We just currently download manually from here (simply because amount of machines is not too large).
https://xcodereleases.com

But thanks for the scripts though, they look quite great 👍 . Is there some public docs on how to use those provisioning scripts you have? I could try them out on our machines as well. I remember I was even told once that there are some possibilities for automation for adding new runners available.

_(In that sense I don't think there's much conceptual difference between github agents and self-hosted machines, it's still a bunch of probably non-virtualised macs connected to some rack in some datacenter where you have accesses with SSH / remote desktop to provision)_

---

> @dentuzhik , Can't promise anything but could you please log an issue in this repository and I will think over this request. Also it would be very helpful if you may share the structure of your Xcode installation (naming and etc).

I will try to draft something next week 👨‍💻 

---

> P.S. Just for curiosity, why do you use fork of this action? If you worry that you can be broken by any new changes, you can just pin specific version like v1.2 (or even specific commit)

There are two considerations here

First as you mentioned it, the versioning scheme. While it's possible to freeze package to a tag on our side, it is still equally possible to push and overwrite the tag (and to my knowledge it has been done occasionally for other `actions/*`) and that's a way to avoid both security and backwards compatibility risk.

Second, is that for any organisation running third party code on own hardware, you need to be sure that it doesn't do any shenanigans, and while fork is not an ideal solution for that, combined with possibility mentioned in paragraph before, I would opt in more control. 

When syncing the fork I can diff all the changes manually and see that nothing does anything suspicious, and also test changes on non-production code snapshots. It's a requirement which obviously comes into play when you run it on self-hosted runners, and I understand that you might not have designed your action for this.

I know that you are working with Github, but our policies do not explicitly allow to have non `actions/*` actions). Would these actions be part of official actions repository, we would likely not use the fork at all.

**Comment by maxim-lobanov** [comment]
> Is there some public docs on how to use those provisioning scripts you have? I could try them out on our machines as well. I remember I was even told once that there are some possibilities for automation for adding new runners available.

@dentuzhik , Unfortunately, not yet. MacOS source code was just open sourced ~4 weeks ago.
The general process is pretty same like for Ubuntu / Windows images. Packer run all scripts from https://github.com/actions/virtual-environments/blob/main/images/macos/templates/macOS-10.15.json one by one.
-  [xcode-tools.sh](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/xcode-tools.sh) contains general logic to install Xcode versions to VM.
- It uses some helper functions from [xcode-utils.sh](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/utils/xcode-utils.sh)
- The list of Xcode to install is stored in [toolset-10.15.json](https://github.com/actions/virtual-environments/blob/main/images/macos/toolsets/toolset-10.15.json) to simplify overriding in custom builds. Probably, you can simply replace reading from json by the list of Xcode

> There are two considerations here
Got it, that makes sense.
Yep, this action should not be considered as official one because it is just my hobby-project and attempt to improve Xcode using UX on GitHub images. I don't think that it can be included to actions org due to maintenance concerns.

**Pull request merged**
